# Generated by Django 5.0.3 on 2024-04-17 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_userprofile_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
