# Generated by Django 5.0.3 on 2024-04-18 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_userprofile_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='author',
            new_name='user',
        ),
    ]
